var languageList = [
	{"labels" : { "fr" : "Allemand", "en" : "German"}, "code": "DEU"},
	{"labels" : { "fr" : "Anglais", "en" : "English"}, "code": "ENG"},
	{"labels" : { "fr" : "Arabe", "en" : "Arabic"}, "code": "ARA"},
	{"labels" : { "fr" : "Chinois", "en" : "Chinese"}, "code": "CHI"},
	{"labels" : { "fr" : "Coréen", "en" : "Korean"}, "code": "KOR"},
	{"labels" : { "fr" : "Danois", "en" : "Danish"}, "code": "DAN"},
	{"labels" : { "fr" : "Espagnol", "en" : "Spanish"}, "code": "ESL"},
	{"labels" : { "fr" : "Français", "en" : "French"}, "code": "FRA"},
	{"labels" : { "fr" : "Grec", "en" : "Greek"}, "code": "ELL"},
	{"labels" : { "fr" : "Hébreu", "en" : "Hebrew"}, "code": "HEB"},
	{"labels" : { "fr" : "Hindi", "en" : "Hindi"}, "code": "HIN"},
	{"labels" : { "fr" : "Hongrois", "en" : "Hungarian"}, "code": "HUN"},
	{"labels" : { "fr" : "Iraniennes", "en" : "Iranian"}, "code": "IRA"},
	{"labels" : { "fr" : "Islandais", "en" : "Icelandic"}, "code": "ICE"},
	{"labels" : { "fr" : "Italien", "en" : "Italian"}, "code": "ITA"},
	{"labels" : { "fr" : "Japonais", "en" : "Japanese"}, "code": "JPN"},
	{"labels" : { "fr" : "Kurde", "en" : "Kurdish"}, "code": "KUR"},
	{"labels" : { "fr" : "Mongol", "en" : "Mongolian"}, "code": "MON"},
	{"labels" : { "fr" : "Muet", "en" : "mute"}, "code": "MUE"},
	{"labels" : { "fr" : "Néerlandais", "en" : "Dutch"}, "code": "DUT"},
	{"labels" : { "fr" : "Norvégien", "en" : "Norwegian"}, "code": "NOR"},
	{"labels" : { "fr" : "Polonais", "en" : "Polish"}, "code": "POL"},
	{"labels" : { "fr" : "Portugais", "en" : "Portuguese"}, "code": "POR"},
	{"labels" : { "fr" : "Roumain", "en" : "Romanian"}, "code": "RON"},
	{"labels" : { "fr" : "Russe", "en" : "Russian"}, "code": "RUS"},
	{"labels" : { "fr" : "serbe", "en" : "Serbian"}, "code": "SCC"},
	{"labels" : { "fr" : "Suédois", "en" : "Swedish"}, "code": "SVE"},
	{"labels" : { "fr" : "Tchèque", "en" : "Czech"}, "code": "CES"},
	{"labels" : { "fr" : "Thaï", "en" : "Thai"}, "code": "THA"},
	{"labels" : { "fr" : "Turc", "en" : "Turkish"}, "code": "TUR"},
	{"labels" : { "fr" : "Vietnamien", "en" : "Vietnamese"}, "code": "VIE"}
];

